//app specific actions
export const POST_FEEDBACK_REQUEST = 'POST_FEEDBACK_REQUEST';
export const POST_FEEDBACK_SUCCESS = 'POST_FEEDBACK_SUCCESS';
export const POST_FEEDBACK_FAILURE = 'POST_FEEDBACK_FAILURE';


export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

//login with OTP: 
export const LOGIN_VALIDATE_MOBILE_REQUEST = 'LOGIN_VALIDATE_MOBILE_REQUEST';
export const LOGIN_VALIDATE_MOBILE_SUCCESS = 'LOGIN_VALIDATE_MOBILE_SUCCESS';
export const LOGIN_VALIDATE_MOBILE_FAILURE = 'LOGIN_VALIDATE_MOBILE_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
//export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const REGISTER_MOBILE_REQUEST = 'REGISTER_MOBILE_REQUEST';
export const REGISTER_MOBILE_SUCCESS = 'REGISTER_MOBILE_SUCCESS';
export const REGISTER_MOBILE_FAILURE = 'REGISTER_MOBILE_FAILURE';

//OTP r
export const GENERATE_OTP_REQUEST = 'GENERATE_OTP_REQUEST';
export const GENERATE_OTP_SUCCESS = 'GENERATE_OTP_SUCCESS';
export const GENERATE_OTP_FAILURE = 'GENERATE_OTP_FAILURE';

export const VALIDATE_OTP_REQUEST = 'VALIDATE_OTP_REQUEST';
export const VALIDATE_OTP_SUCCESS = 'VALIDATE_OTP_SUCCESS';
export const VALIDATE_OTP_FAILURE = 'VALIDATE_OTP_FAILURE';
//register user
export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';

// 


//user profile actions

export const FETCH_USER_PROFILE_DETAILS_REQUESTED = 'FETCH_USER_PROFILE_DETAILS_REQUESTED';
export const FETCH_USER_PROFILE_DETAILS_SUCCESS = 'FETCH_USER_PROFILE_DETAILS_SUCCESS';
export const FETCH_USER_PROFILE_DETAILS_FAILED = 'FETCH_USER_PROFILE_DETAILS_FAILED';

export const SAVE_USER_PROFILE_DETAILS_REQUESTED = 'SAVE_USER_PROFILE_DETAILS_REQUESTED';
export const SAVE_USER_PROFILE_DETAILS_SUCCESS = 'SAVE_USER_PROFILE_DETAILS_SUCCESS';
export const SAVE_USER_PROFILE_DETAILS_FAILED = 'SAVE_USER_PROFILE_DETAILS_FAILED';


export const UPDATE_USER_PERSOANAL_DETAILS_REQUESTED = 'UPDATE_USER_PERSOANAL_DETAILS_REQUESTED';
export const UPDATE_USER_PERSOANAL_DETAILS_SUCCESS = 'UPDATE_USER_PERSOANAL_DETAILS_SUCCESS';
export const UPDATE_USER_PERSOANAL_DETAILS_FAILED = 'UPDATE_USER_PERSOANAL_DETAILS_FAILED';
//user sharing information
export const UPDATE_USER_SHARING_DETAILS_REQUESTED = 'UPDATE_USER_SHARING_DETAILS_REQUESTED';
export const UPDATE_USER_SHARING_DETAILS_SUCCESS = 'UPDATE_USER_SHARING_DETAILS_SUCCESS';
export const UPDATE_USER_SHARING_DETAILS_FAILED = 'UPDATE_USER_SHARING_DETAILS_FAILED';

//Scan code:

//user sharing information
export const VALIDATE_QR_CODE_REQUESTED = 'VALIDATE_QR_CODE_REQUESTED';
export const VALIDATE_QR_CODE_SUCCESS = 'VALIDATE_QR_CODE_SUCCESS';
export const VALIDATE_QR_CODE_FAILED = 'VALIDATE_QR_CODE_FAILED';

//user contact list information
export const FETCH_USER_CONTACT_LIST_REQUESTED = 'FETCH_USER_CONTACT_LIST_REQUESTED';
export const FETCH_USER_CONTACT_LIST_SUCCESS = 'FETCH_USER_CONTACT_LIST_SUCCESS';
export const FETCH_USER_CONTACT_LIST_FAILED = 'FETCH_USER_CONTACT_LIST_FAILED';

//user profile pic upload
export const UPDATE_PROFILE_PIC_REQUESTED = 'UPDATE_PROFILE_PIC_REQUESTED'
export const UPDATE_PROFILE_PIC_SUCCESS = 'UPDATE_PROFILE_PIC_SUCCESS'
export const UPDATE_PROFILE_PIC_FAILED = 'UPDATE_PROFILE_PIC_FAILED'

