export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
//export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const REGISTER_MOBILE_REQUEST = 'REGISTER_MOBILE_REQUEST';
export const REGISTER_MOBILE_SUCCESS = 'REGISTER_MOBILE_SUCCESS';
export const REGISTER_MOBILE_FAILURE = 'REGISTER_MOBILE_FAILURE';

//OTP r
export const GENERATE_OTP_REQUEST = 'GENERATE_OTP_REQUEST';
export const GENERATE_OTP_SUCCESS = 'GENERATE_OTP_SUCCESS';
export const GENERATE_OTP_FAILURE = 'GENERATE_OTP_FAILURE';

export const VALIDATE_OTP_REQUEST = 'VALIDATE_OTP_REQUEST';
export const VALIDATE_OTP_SUCCESS = 'VALIDATE_OTP_SUCCESS';
export const VALIDATE_OTP_FAILURE = 'VALIDATE_OTP_FAILURE';
//register user
export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';

// 
export const SETUP_CHAT_CONNECTION = 'SETUP_CHAT_CONNECTION';
//CHAT LIST
export const FETCH_CHAT_LIST_REQUEST = 'FETCH_CHAT_LIST_REQUEST';
export const FETCH_CHAT_LIST_SUCCESS = 'FETCH_CHAT_LIST_SUCCESS';
export const FETCH_CHAT_LIST_FAILURE = 'FETCH_CHAT_LIST_FAILURE';


//CHAT MESSAGES
export const FETCH_CHAT_MESSAGES_REQUEST = 'FETCH_CHAT_MESSAGES_REQUEST';
export const FETCH_CHAT_MESSAGES_SUCCESS = 'FETCH_CHAT_MESSAGES_SUCCESS';
export const FETCH_CHAT_MESSAGES_FAILURE = 'FETCH_CHAT_MESSAGES_FAILURE';

//event for on going CHAT MESSAGES
export const LISTEN_ONGOING_CHAT_MESSAGES = 'LISTEN_ONGOING_CHAT_MESSAGES';
export const CLOSE_ONGOING_CHAT_MESSAGES = 'CLOSE_ONGOING_CHAT_MESSAGES';
export const GOT_NEW_ONGOING_CHAT_MESSAGE = 'GOT_NEW_ONGOING_CHAT_MESSAGE'


//event for NEW  CHAT MESSAGES
export const LISTEN_NEW_CHAT_MESSAGES = 'LISTEN_NEW_CHAT_MESSAGES_REQUEST';
export const LISTEN_NEW_CHAT_MESSAGES_SUCCESS = 'LISTEN_NEW_CHAT_MESSAGES_SUCCESS';
export const LISTEN_NEW_CHAT_MESSAGES_FAILURE = 'LISTEN_NEW_CHAT_MESSAGES_FAILURE';



//chat messages
export const GOT_MESSAGES = 'GOT_MESSAGES';
export const GOT_NEW_MESSAGE = 'GOT_NEW_MESSAGE';
export const SEND_NEW_MESSAGE = 'SEND_NEW_MESSAGE';
export const RESET_MESSAGE_REDUCER = 'RESET_MESSAGE_REDUCER';


//incoming calls
export const LISTEN_INCOMING_REQUEST = 'LISTEN_INCOMING_REQUEST';
export const LISTEN_INCOMING_SUCCESS = 'LISTEN_INCOMING_SUCCESS';
export const OUTGOING_CALL_REQUEST = 'OUTGOING_CALL_REQUEST';
export const CALL_END = 'CALL_END';
//WHEN THE component unmounts : 
export const RESET_CALL_STATE = 'RESET_CALL_STATE';
export const RESET_BUSY_STATE = 'RESET_BUSY_STATE'

//toggle online consulation status :
export const TOGGLE_ONLINE_STATUS_REQUESTED = 'TOGGLE_ONLINE_STATUS_REQUESTED';
export const TOGGLE_ONLINE_STATUS_SUCESS = 'TOGGLE_ONLINE_STATUS_SUCESS';


//user profile actions

export const FETCH_USER_PROFILE_DETAILS_REQUESTED = 'FETCH_USER_PROFILE_DETAILS_REQUESTED';
export const FETCH_USER_PROFILE_DETAILS_SUCCESS = 'FETCH_USER_PROFILE_DETAILS_SUCCESS';
export const FETCH_USER_PROFILE_DETAILS_FAILED = 'FETCH_USER_PROFILE_DETAILS_FAILED';

export const SAVE_USER_PROFILE_DETAILS_REQUESTED = 'SAVE_USER_PROFILE_DETAILS_REQUESTED';
export const SAVE_USER_PROFILE_DETAILS_SUCCESS = 'SAVE_USER_PROFILE_DETAILS_SUCCESS';
export const SAVE_USER_PROFILE_DETAILS_FAILED = 'SAVE_USER_PROFILE_DETAILS_FAILED';

export const SEARCH_CONSULTANT_REQUESTED = 'SEARCH_CONSULTANT_REQUESTED';
export const SEARCH_CONSULTANT_SUCCESS = 'SEARCH_CONSULTANT_SUCCESS';
export const SEARCH_CONSULTANT_FAILED = 'SEARCH_CONSULTANT_FAILED';
//FETCH CONSULTANT
export const FETCH_CONSULTANT_DETAILS_REQUESTED = 'FETCH_CONSULTANT_DETAILS_REQUESTED';
export const FETCH_CONSULTANT_DETAILS_SUCCESS = 'FETCH_CONSULTANT_DETAILS_SUCCESS';
export const FETCH_CONSULTANT_DETAILS_FAILED = 'FETCH_CONSULTANT_DETAILS_FAILED';


export const UPDATE_USER_PERSOANAL_DETAILS_REQUESTED = 'UPDATE_USER_PERSOANAL_DETAILS_REQUESTED';
export const UPDATE_USER_PERSOANAL_DETAILS_SUCCESS = 'UPDATE_USER_PERSOANAL_DETAILS_SUCCESS';
export const UPDATE_USER_PERSOANAL_DETAILS_FAILED = 'UPDATE_USER_PERSOANAL_DETAILS_FAILED';

//residential address :
export const UPDATE_USER_ADDRESS_REQUESTED = 'UPDATE_USER_ADDRESS_REQUESTED';
export const UPDATE_USER_ADDRESS_SUCCESS = 'UPDATE_USER_ADDRESS_SUCCESS';
export const UPDATE_USER_ADDRESS_FAILED = 'UPDATE_USER_ADDRESS_FAILED';

//family members
//residential address :

export const FETCH_USER_RELATIVES_REQUESTED = 'FETCH_USER_RELATIVES_REQUESTED';
export const FETCH_USER_RELATIVES_SUCCESS = 'FETCH_USER_RELATIVES_SUCCESS';
export const FETCH_USER_RELATIVES_FAILED = 'FETCH_USER_RELATIVES_FAILED';

export const UPDATE_USER_RELATIVES_REQUESTED = 'UPDATE_USER_RELATIVES_REQUESTED';
export const UPDATE_USER_RELATIVES_SUCCESS = 'UPDATE_USER_RELATIVES_SUCCESS';
export const UPDATE_USER_RELATIVES_FAILED = 'UPDATE_USER_RELATIVES_FAILED';

export const DELETE_USER_RELATIVES_REQUESTED = 'DELETE_USER_RELATIVES_REQUESTED';
export const DELETE_USER_RELATIVES_SUCCESS = 'DELETE_USER_RELATIVES_SUCCESS';
export const DELETE_USER_RELATIVES_FAILED = 'DELETE_USER_RELATIVES_FAILED';

//permanenet address:

export const UPDATE_USER_PERMANENET_ADDRESS_REQUESTED = 'UPDATE_USER_PERMANENET_ADDRESS_REQUESTED';
export const UPDATE_USER_PERMANENET_ADDRESS_SUCCESS = 'UPDATE_USER_PERMANENET_ADDRESS_SUCCESS';
export const UPDATE_USER_PERMANENET_ADDRESS_FAILED = 'UPDATE_USER_PERMANENET_ADDRESS_FAILED';

export const FETCH_COUNTRY_REQUESTED = 'FETCH_COUNTRY_REQUESTED'
export const FETCH_COUNTRY_SUCCESS = 'FETCH_COUNTRY_SUCCESS'
export const FETCH_COUNTRY_FAILED = 'FETCH_COUNTRY_FAILED'

export const FETCH_STATE_REQUESTED = 'FETCH_STATE_REQUESTED'
export const FETCH_STATE_SUCCESS = 'FETCH_STATE_SUCCESS'
export const FETCH_STATE_FAILED = 'FETCH_STATE_FAILED'

export const FETCH_CITY_REQUESTED = 'FETCH_CITY_REQUESTED'
export const FETCH_CITY_SUCCESS = 'FETCH_CITY_SUCCESS'
export const FETCH_CITY_FAILED = 'FETCH_CITY_FAILED'

//permanent address
export const FETCH_PERMANENT_ADDR_STATE_REQUESTED = 'FETCH_PERMANENT_ADDR_STATE_REQUESTED'
export const FETCH_PERMANENT_ADDR_STATE_SUCCESS = 'FETCH_PERMANENT_ADDR_STATE_SUCCESS'
export const FETCH_PERMANENT_ADDR_STATE_FAILED = 'FETCH_PERMANENT_ADDR_STATE_FAILED'

export const FETCH_PERMANENT_ADDR_CITY_REQUESTED = 'FETCH_PERMANENT_ADDR_CITY_REQUESTED'
export const FETCH_PERMANENT_ADDR_CITY_SUCCESS = 'FETCH_PERMANENT_ADDR_CITY_SUCCESS'
export const FETCH_PERMANENT_ADDR_CITY_FAILED = 'FETCH_PERMANENT_ADDR_CITY_FAILED'

//profesional 

export const FETCH_ROLES_REQUESTED = 'FETCH_ROLES_REQUESTED'
export const FETCH_ROLES_SUCCESS = 'FETCH_ROLES_SUCCESS'
export const FETCH_ROLES_FAILED = 'FETCH_ROLES_FAILED'

//services
export const FETCH_SERVICES_REQUESTED = 'FETCH_SERVICES_REQUESTED'
export const FETCH_SERVICES_SUCCESS = 'FETCH_SERVICES_SUCCESS'
export const FETCH_SERVICES_FAILED = 'FETCH_SERVICES_FAILED'

export const UPDATE_ROLES_REQUESTED = 'UPDATE_ROLES_REQUESTED'
export const UPDATE_ROLES_SUCCESS = 'UPDATE_ROLES_SUCCESS'
export const UPDATE_ROLES_FAILED = 'UPDATE_ROLES_FAILED'

//streams
export const FETCH_STREAMS_REQUESTED = 'FETCH_STREAMS_REQUESTED'
export const FETCH_STREAMS_SUCCESS = 'FETCH_STREAMS_SUCCESS'
export const FETCH_STREAMS_FAILED = 'FETCH_STREAMS_FAILED'

export const UPDATE_STREAMS_REQUESTED = 'UPDATE_STREAMS_REQUESTED'
export const UPDATE_STREAMS_SUCCESS = 'UPDATE_STREAMS_SUCCESS'
export const UPDATE_STREAMS_FAILED = 'UPDATE_STREAMS_FAILED'

export const DELETE_STREAM_REQUESTED = 'DELETE_STREAM_REQUESTED'
export const DELETE_STREAM_SUCCESS = 'DELETE_STREAM_SUCCESS'
export const DELETE_STREAM_FAILED = 'DELETE_STREAM_FAILED'

//qualification

export const FETCH_QUALIFICATION_REQUESTED = 'FETCH_QUALIFICATION_REQUESTED'
export const FETCH_QUALIFICATION_SUCCESS = 'FETCH_QUALIFICATION_SUCCESS'
export const FETCH_QUALIFICATION_FAILED = 'FETCH_QUALIFICATION_FAILED'
//add qualification
export const ADD_QUALIFICATION_REQUESTED = 'ADD_QUALIFICATION_REQUESTED'
export const ADD_QUALIFICATION_SUCCESS = 'ADD_QUALIFICATION_SUCCESS'
export const ADD_QUALIFICATION_FAILED = 'ADD_QUALIFICATION_FAILED'
//update 
export const UPDATE_QUALIFICATION_REQUESTED = 'UPDATE_QUALIFICATION_REQUESTED'
export const UPDATE_QUALIFICATION_SUCCESS = 'UPDATE_QUALIFICATION_SUCCESS'
export const UPDATE_QUALIFICATION_FAILED = 'UPDATE_QUALIFICATION_FAILED'
//DELETE QUALIFICATION
export const DELETE_QUALIFICATION_REQUESTED = 'DELETE_QUALIFICATION_REQUESTED'
export const DELETE_QUALIFICATION_SUCCESS = 'DELETE_QUALIFICATION_SUCCESS'
export const DELETE_QUALIFICATION_FAILED = 'DELETE_QUALIFICATION_FAILED'

//speciality

export const FETCH_SPECIALITY_REQUESTED = 'FETCH_SPECIALITY_REQUESTED'
export const FETCH_SPECIALITY_SUCCESS = 'FETCH_SPECIALITY_SUCCESS'
export const FETCH_SPECIALITY_FAILED = 'FETCH_SPECIALITY_FAILED'


//super speciality

export const FETCH_SUPER_SPECIALITY_REQUESTED = 'FETCH_SUPER_SPECIALITY_REQUESTED'
export const FETCH_SUPER_SPECIALITY_SUCCESS = 'FETCH_SUPER_SPECIALITY_SUCCESS'
export const FETCH_SUPER_SPECIALITY_FAILED = 'FETCH_SUPER_SPECIALITY_FAILED'

//common symptoms

export const FETCH_COMMON_SYMPTOMS_REQUESTED = 'FETCH_COMMON_SYMPTOMS_REQUESTED'
export const FETCH_COMMON_SYMPTOMS_SUCCESS = 'FETCH_COMMON_SYMPTOMS_SUCCESS'
export const FETCH_COMMON_SYMPTOMS_FAILED = 'FETCH_COMMON_SYMPTOMS_FAILED'

//all symptoms
export const FETCH_ALL_SYMPTOMS_REQUESTED = 'FETCH_ALL_SYMPTOMS_REQUESTED'
export const FETCH_ALL_SYMPTOMS_SUCCESS = 'FETCH_ALL_SYMPTOMS_SUCCESS'
export const FETCH_ALL_SYMPTOMS_FAILED = 'FETCH_ALL_SYMPTOMS_FAILED'


//search symptoms
export const SEARCH_SYMPTOMS_REQUESTED = 'SEARCH_SYMPTOMS_REQUESTED'
export const SEARCH_SYMPTOMS_SUCCESS = 'SEARCH_SYMPTOMS_SUCCESS'
export const SEARCH_ALL_SYMPTOMS_FAILED = 'SEARCH_ALL_SYMPTOMS_FAILED'

//emr api's

export const SEARCH_ICDS_REQUESTED = 'SEARCH_ICDS_REQUESTED'
export const SEARCH_ICDS_SUCCESS = 'SEARCH_ICDS_SUCCESS'
export const SEARCH_ICDS_FAILED = 'SEARCH_ICDS_FAILED'


//emr api's

export const SEARCH_DRUGS_REQUESTED = 'SEARCH_DRUGS_REQUESTED'
export const SEARCH_DRUGS_SUCCESS = 'SEARCH_DRUGS_SUCCESS'
export const SEARCH_DRUGS_FAILED = 'SEARCH_DRUGS_FAILED'


//all CARE PLAN
export const FETCH_ALL_CARE_PLAN_REQUESTED = 'FETCH_ALL_CARE_PLAN_REQUESTED'
export const FETCH_ALL_CARE_PLAN_SUCCESS = 'FETCH_ALL_CARE_PLAN_SUCCESS'
export const FETCH_ALL_CARE_PLAN_FAILED = 'FETCH_ALL_CARE_PLAN_FAILED'



//all PRODECURES
export const FETCH_ALL_PROCEDURES_REQUESTED = 'FETCH_ALL_PROCEDURES_REQUESTED'
export const FETCH_ALL_PROCEDURES_SUCCESS = 'FETCH_ALL_PROCEDURES_SUCCESS'
export const FETCH_ALL_PROCEDURES_FAILED = 'FETCH_ALL_PROCEDURES_FAILED'


//all DIAGONOSTIC TEST
export const FETCH_ALL_DIAGONISTIC_TEST_REQUESTED = 'FETCH_ALL_DIAGONISTIC_TEST_REQUESTED'
export const FETCH_ALL_DIAGONISTIC_TEST_SUCCESS = 'FETCH_ALL_DIAGONISTIC_TEST_SUCCESS'
export const FETCH_ALL_DIAGONISTIC_TEST_FAILED = 'FETCH_ALL_DIAGONISTIC_TEST_FAILED'



export const UPDATE_SPECIALITY_REQUESTED = 'UPDATE_SPECIALITY_REQUESTED'
export const UPDATE_SPECIALITY_SUCCESS = 'UPDATE_SPECIALITY_SUCCESS'
export const UPDATE_SPECIALITY_FAILED = 'UPDATE_SPECIALITY_FAILED'

export const UPDATE_SUPER_SPECIALITY_REQUESTED = 'UPDATE_SUPER_SPECIALITY_REQUESTED'
export const UPDATE_SUPER_SPECIALITY_SUCCESS = 'UPDATE_SUPER_SPECIALITY_SUCCESS'
export const UPDATE_SUPER_SPECIALITY_FAILED = 'UPDATE_SUPER_SPECIALITY_FAILED'




export const DELETE_SPECIALITY_REQUESTED = 'DELETE_SPECIALITY_REQUESTED'
export const DELETE_SPECIALITY_SUCCESS = 'DELETE_SPECIALITY_SUCCESS'
export const DELETE_SPECIALITY_FAILED = 'DELETE_SPECIALITY_FAILED'


export const UPDATE_PROFESSIONAL_INFO_REQUESTED = 'UPDATE_PROFESSIONAL_INFO_REQUESTED'
export const UPDATE_PROFESSIONAL_INFO_SUCCESS = 'UPDATE_PROFESSIONAL_INFO_SUCCESS'
export const UPDATE_PROFESSIONAL_INFO_FAILED = 'UPDATE_PROFESSIONAL_INFO_FAILED'

//family physician

export const UPDATE_FAMILY_PHYSICIAN_REQUESTED = 'UPDATE_FAMILY_PHYSICIAN_REQUESTED'
export const UPDATE_FAMILY_PHYSICIAN_SUCCESS = 'UPDATE_FAMILY_PHYSICIAN_SUCCESS'
export const UPDATE_FAMILY_PHYSICIAN_FAILED = 'UPDATE_FAMILY_PHYSICIAN_FAILED'


export const UPDATE_PROFILE_PIC_REQUESTED = 'UPDATE_PROFILE_PIC_REQUESTED'
export const UPDATE_PROFILE_PIC_SUCCESS = 'UPDATE_PROFILE_PIC_SUCCESS'
export const UPDATE_PROFILE_PIC_FAILED = 'UPDATE_PROFILE_PIC_FAILED'

//working with us 
//home services
export const CREATE_HOME_VISIT_REQUESTED = 'CREATE_HOME_VISIT_REQUESTED'
export const CREATE_HOME_VISIT_SUCCESS = 'CREATE_HOME_VISIT_SUCCESS'
export const CREATE_HOME_VISIT_FAILED = 'CREATE_HOME_VISIT_FAILED'

//update
export const UPDATE_HOME_VISIT_REQUESTED = 'UPDATE_HOME_VISIT_REQUESTED'
export const UPDATE_HOME_VISIT_SUCCESS = 'UPDATE_HOME_VISIT_SUCCESS'
export const UPDATE_HOME_VISIT_FAILED = 'UPDATE_HOME_VISIT_FAILED'

//DELETE
export const DELETE_HOME_VISIT_REQUESTED = 'DELETE_HOME_VISIT_REQUESTED'
export const DELETE_HOME_VISIT_SUCCESS = 'DELETE_HOME_VISIT_SUCCESS'
export const DELETE_HOME_VISIT_FAILED = 'DELETE_HOME_VISIT_FAILED'

//DELETE all
export const DELETE_USER_ALL_HOME_VISIT_REQUESTED = 'DELETE_USER_ALL_HOME_VISIT_REQUESTED'
export const DELETE_USER_ALL_HOME_VISIT_SUCCESS = 'DELETE_USER_ALL_HOME_VISIT_SUCCESS'
export const DELETE_USER_ALL_HOME_VISIT_FAILED = 'DELETE_USER_ALL_HOME_VISIT_FAILED'

//ambulance services
export const CREATE_AMBULANCE_SERVICE_REQUESTED = 'CREATE_AMBULANCE_SERVICE_REQUESTED'
export const CREATE_AMBULANCE_SERVICE_SUCCESS = 'CREATE_AMBULANCE_SERVICE_SUCCESS'
export const CREATE_AMBULANCE_SERVICE_FAILED = 'CREATE_AMBULANCE_SERVICE_FAILED'

export const UPDATE_AMBULANCE_SERVICE_REQUESTED = 'UPDATE_AMBULANCE_SERVICE_REQUESTED'
export const UPDATE_AMBULANCE_SERVICE_SUCCESS = 'UPDATE_AMBULANCE_SERVICE_SUCCESS'
export const UPDATE_AMBULANCE_SERVICE_FAILED = 'UPDATE_AMBULANCE_SERVICE_FAILED'

//delete
export const DELETE_AMBULANCE_SERVICE_REQUESTED = 'DELETE_AMBULANCE_SERVICE_REQUESTED'
export const DELETE_AMBULANCE_SERVICE_SUCCESS = 'DELETE_AMBULANCE_SERVICE_SUCCESS'
export const DELETE_AMBULANCE_SERVICE_FAILED = 'DELETE_AMBULANCE_SERVICE_FAILED'

//delete all
export const DELETE_USER_ALL_AMBULANCE_SERVICE_REQUESTED = 'DELETE_USER_ALL_AMBULANCE_SERVICE_REQUESTED'
export const DELETE_USER_ALL__AMBULANCE_SERVICE_SUCCESS = 'DELETE_USER_ALL__AMBULANCE_SERVICE_SUCCESS'
export const DELETE_USER_ALL__AMBULANCE_SERVICE_FAILED = 'DELETE_USER_ALL__AMBULANCE_SERVICE_FAILED'

////tpa create
export const CREATE_TPA_REQUESTED = 'CREATE_TPA_REQUESTED'
export const CREATE_TPA_SUCCESS = 'CREATE_TPA_SUCCESS'
export const CREATE_TPA_FAILED = 'CREATE_TPA_FAILED'

////tpa create
export const UPDATE_TPA_REQUESTED = 'UPDATE_TPA_REQUESTED'
export const UPDATE_TPA_SUCCESS = 'UPDATE_TPA_SUCCESS'
export const UPDATE_TPA_FAILED = 'UPDATE_TPA_FAILED'

////tpa DELETE
export const DELETE_TPA_REQUESTED = 'DELETE_TPA_REQUESTED'
export const DELETE_TPA_SUCCESS = 'DELETE_TPA_SUCCESS'
export const DELETE_TPA_FAILED = 'DELETE_TPA_FAILED'

////tpa ALL DELETE
export const DELETE_ALL_USER_TPA_REQUESTED = 'DELETE_ALL_USER_TPA_REQUESTED'
export const DELETE_ALL_USER_TPA_SUCCESS = 'DELETE_ALL_USER_TPA_SUCCESS'
export const DELETE_ALL_USER__TPA_FAILED = 'DELETE_ALL_USER__TPA_FAILED'

//online consulation
//
export const CREATE_ONLINE_COSULTATION_REQUESTED = 'CREATE_ONLINE_COSULTATION_REQUESTED'
export const CREATE_ONLINE_COSULTATION_SUCCESS = 'CREATE_ONLINE_COSULTATION_SUCCESS'
export const CREATE_ONLINE_COSULTATION_FAILED = 'CREATE_ONLINE_COSULTATION_FAILED'
//update
export const UPDATE_ONLINE_COSULTATION_REQUESTED = 'UPDATE_ONLINE_COSULTATION_REQUESTED'
export const UPDATE_ONLINE_COSULTATION_SUCCESS = 'UPDATE_ONLINE_COSULTATION_SUCCESS'
export const UPDATE_ONLINE_COSULTATION_FAILED = 'UPDATE_ONLINE_COSULTATION_FAILED'
//delete
export const DELETE_ONLINE_COSULTATION_REQUESTED = 'DELETE_ONLINE_COSULTATION_REQUESTED'
export const DELETE_ONLINE_COSULTATION_SUCCESS = 'DELETE_ONLINE_COSULTATION_SUCCESS'
export const DELETE_ONLINE_COSULTATION_FAILED = 'DELETE_ONLINE_COSULTATION_FAILED'

//home visit type
//online consulation
//
export const FETCH_HOME_VISIT_TYPE_REQUESTED = 'FETCH_HOME_VISIT_TYPE_REQUESTED'
export const FETCH_HOME_VISIT_TYPE_SUCCESS = 'FETCH_HOME_VISIT_TYPE_SUCCESS'
export const FETCH_HOME_VISIT_TYPE_FAILED = 'FETCH_HOME_VISIT_TYPE_FAILED'

//ambulance type
export const FETCH_AMBULANCE_TYPE_REQUESTED = 'FETCH_AMBULANCE_TYPE_REQUESTED'
export const FETCH_AMBULANCE_TYPE_SUCCESS = 'FETCH_AMBULANCE_TYPE_SUCCESS'
export const FETCH_AMBULANCE_TYPE_FAILED = 'FETCH_AMBULANCE_TYPE_FAILED'
//tpa type
export const FETCH_TPA_TYPE_REQUESTED = 'FETCH_TPA_TYPE_REQUESTED'
export const FETCH_TPA_TYPE_SUCCESS = 'FETCH_TPA_TYPE_SUCCESS'
export const FETCH_TPA_TYPE_FAILED = 'FETCH_TPA_TYPE_FAILED'

//locum fetch
export const FETCH_LOCUM_REQUESTED = 'FETCH_LOCUM_REQUESTED'
export const FETCH_LOCUM_SUCCESS = 'FETCH_LOCUM_SUCCESS'
export const FETCH_LOCUM_FAILED = 'FETCH_LOCUM_FAILED'
//locum save
export const CREATE_LOCUM_REQUESTED = 'CREATE_LOCUM_REQUESTED'
export const CREATE_LOCUM_SUCCESS = 'CREATE_LOCUM_SUCCESS'
export const CREATE_LOCUM_FAILED = 'CREATE_LOCUM_FAILED'

//locum save
export const UPDATE_LOCUM_REQUESTED = 'UPDATE_LOCUM_REQUESTED'
export const UPDATE_LOCUM_SUCCESS = 'UPDATE_LOCUM_SUCCESS'
export const UPDATE_LOCUM_FAILED = 'UPDATE_LOCUM_FAILED'
//locum delete
export const DELETE_LOCUM_REQUESTED = 'DELETE_LOCUM_REQUESTED'
export const DELETE_LOCUM_SUCCESS = 'DELETE_LOCUM_SUCCESS'
export const DELETE_LOCUM_FAILED = 'DELETE_LOCUM_FAILED'

//locum all delete
export const DELETE_ALL_USER_LOCUM_REQUESTED = 'DELETE_ALL_USER_LOCUM_REQUESTED'
export const DELETE_ALL_USER_LOCUM_SUCCESS = 'DELETE_ALL_USER_LOCUM_SUCCESS'
export const DELETE_ALL_USER_LOCUM_FAILED = 'DELETE_ALL_USER_LOCUM_FAILED'
//appointment

export const CREATE_DOCTOR_APPOINTMENT_INFO_REQUESTED = 'CREATE_DOCTOR_APPOINTMENT_INFO_REQUESTED'
export const CREATE_DOCTOR_APPOINTMENT_INFO_SUCCESS = 'CREATE_DOCTOR_APPOINTMENT_INFO_SUCCESS'
export const CREATE_DOCTOR_APPOINTMENT_INFO_FAILED = 'CREATE_DOCTOR_APPOINTMENT_INFO_FAILED'

//update
export const UPDATE_DOCTOR_APPOINTMENT_INFO_REQUESTED = 'UPDATE_DOCTOR_APPOINTMENT_INFO_REQUESTED'
export const UPDATE_DOCTOR_APPOINTMENT_INFO_SUCCESS = 'UPDATE_DOCTOR_APPOINTMENT_INFO_SUCCESS'
export const UPDATE_DOCTOR_APPOINTMENT_INFO_FAILED = 'UPDATE_DOCTOR_APPOINTMENT_INFO_FAILED'

//delete
export const DELETE_DOCTOR_APPOINTMENT_INFO_REQUESTED = 'DELETE_DOCTOR_APPOINTMENT_INFO_REQUESTED'
export const DELETE_DOCTOR_APPOINTMENT_INFO_SUCCESS = 'DELETE_DOCTOR_APPOINTMENT_INFO_SUCCESS'
export const DELETE_DOCTOR_APPOINTMENT_INFO_FAILED = 'DELETE_DOCTOR_APPOINTMENT_INFO_FAILED'
//delete all
export const DELETE_DOCTOR_ALL_APPOINTMENT_INFO_REQUESTED = 'DELETE_DOCTOR_ALL_APPOINTMENT_INFO_REQUESTED'
export const DELETE_DOCTOR_ALL_APPOINTMENT_INFO_SUCCESS = 'DELETE_DOCTOR_ALL_APPOINTMENT_INFO_SUCCESS'
export const DELETE_DOCTOR_ALL_APPOINTMENT_INFO_FAILED = 'DELETE_DOCTOR_ALL_APPOINTMENT_INFO_FAILED'

//subscription plan
export const FETCH_MEMBERSHIP_PLAN_REQUESTED = 'FETCH_MEMBERSHIP_PLAN_REQUESTED'
export const FETCH_MEMBERSHIP_PLAN_SUCCESS = 'FETCH_MEMBERSHIP_PLAN_SUCCESS'
export const FETCH_MEMBERSHIP_PLAN_FAILED = 'FETCH_MEMBERSHIP_PLAN_FAILED'


//user subscription plan
export const FETCH_USER_MEMBERSHIP_PLAN_REQUESTED = 'FETCH_USER_MEMBERSHIP_PLAN_REQUESTED'
export const FETCH_USER_MEMBERSHIP_PLAN_SUCCESS = 'FETCH_USER_MEMBERSHIP_PLAN_SUCCESS'
export const FETCH_USER_MEMBERSHIP_PLAN_FAILED = 'FETCH_USER_MEMBERSHIP_PLAN_FAILED'


//fetch articles

//user subscription plan
export const FETCH_ARTICLES_REQUESTED = 'FETCH_ARTICLES_REQUESTED'
export const FETCH_ARTICLES_SUCCESS = 'FETCH_ARTICLES_SUCCESS'
export const FETCH_ARTICLES_FAILED = 'FETCH_ARTICLES_FAILED'

//fetch user reports
export const FETCH_USER_REPORTS_REQUESTED = 'FETCH_USER_REPORTS_REQUESTED'
export const FETCH_USER_REPORTS_SUCCESS = 'FETCH_USER_REPORTS_SUCCESS'
export const FETCH_USER_REPORTS_FAILED = 'FETCH_USER_REPORTS_FAILED'


